---
version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./build/package/Dockerfile
    image: golang-observer-pattern:1.0.0
    ports:
      - '8080:8080' # Web Server
    volumes:
      - ./:/app
    env_file:
      - .env
